# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Cobin\Desktop\pyqt-gui-template-master\tools\\..\app\ui\about.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(559, 296)
        Dialog.setMinimumSize(QtCore.QSize(410, 296))
        Dialog.setMaximumSize(QtCore.QSize(1484, 296))
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)
        self.imageLabel = QtWidgets.QLabel(Dialog)
        self.imageLabel.setMinimumSize(QtCore.QSize(164, 164))
        self.imageLabel.setObjectName("imageLabel")
        self.gridLayout.addWidget(self.imageLabel, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setMinimumSize(QtCore.QSize(0, 100))
        self.label.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 1, 1, 1)
        self.textLabel = QtWidgets.QLabel(Dialog)
        self.textLabel.setMinimumSize(QtCore.QSize(0, 200))
        self.textLabel.setWordWrap(True)
        self.textLabel.setObjectName("textLabel")
        self.gridLayout.addWidget(self.textLabel, 0, 2, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Wave: About"))
        self.imageLabel.setText(_translate("Dialog", "Image Label"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p>Copyright: Wave is <a href=\"https://github.com/Cobine/Wave/blob/main/LICENSE\"><span style=\" text-decoration: underline; color:#0000ff;\">licensed</span></a> under the GNU General Public Licence v3.0. </p></body></html>"))
        self.textLabel.setText(_translate("Dialog", "<html><head/><body><p>Wave is a standalone library for the processing of waveform accelerometry data from binary AX3 or GENEActiv files to give intensity, and orientation, of monitor statistics at specified time resolutions.</p><p>NIHR Cambridge Biomedical Research Centre – Diet, Anthropometry and Physical Activity Group</p><p><a href=\"https://www.mrc-epid.cam.ac.uk/\"><span style=\" text-decoration: underline; color:#0000ff;\">MRC Epidemiology Unit, Cambridge, UK</span></a></p><p>Version Number: <a href=\"https://github.com/Cobine/Wave/releases\"><span style=\" text-decoration: underline; color:#0000ff;\">XXX</span></a></p><p>Build Date: XXX</p><p><br/></p><p><br/></p></body></html>"))
